services:
  job-recommendation-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-recommendation-engine
    ports:
      - "8082:8080"
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: job-recommendations
    depends_on:
      - kafka
      - trino

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  presto:
    image: prestodb/presto:latest
    container_name: presto
    ports:
      - "8080:8080"
    environment:
      - TRINO_PASSWORD=dev_password
